spring:
  application:
    name: gatewayserver

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway"
    description: "ezyPay apigateway Application"
    version: "1.0.0"

logging:
  level:
    com.microservices.gatewayserver: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway.filter.GatewayMetricsFilter: INFO

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10s

# Optional RabbitMQ settings if needed in future
# rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
