spring:
  application:
    name: gatewayserver

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false  # Keep disabled if using manual routes
              lower-case-service-id: true

          httpclient:
            connect-timeout: 1000
            response-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState

    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway"
    description: "ezyPay apigateway Application"
    version: "1.0.0"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        eventConsumerBufferSize: 10  # Add this if you want to see circuit breaker events
#    instances:
#      accounts:
#        baseConfig: default
#        registerHealthIndicator: true
#      cards:
#        baseConfig: default
#        registerHealthIndicator: true
#      loans:
#        baseConfig: default
#        registerHealthIndicator: true

logging:
  level:
    com.microservices.gatewayserver: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway.filter.GatewayMetricsFilter: INFO
