spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"

# Remove any eureka client configuration from here
# since it will come from the Config Server

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    probes:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true