server:
  port: 8080

spring:
  application:
    name: accounts

  profiles:
    active: prod

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        eventConsumerBufferSize: 10  # Enable event consumption
        recordExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

    instances:
      cards:
        baseConfig: default
        registerHealthIndicator: true

      loans:
        baseConfig: default
        registerHealthIndicator: true

info:
  app:
    name: "accounts"
    description: "ezyPay Accounts Application"
    version: "1.0.0"

logging:
  level:
    com.microservices.accounts: DEBUG
    io.github.resilience4j: DEBUG  # Add this for circuit breaker logs