server:
  port: 8080

spring:
  application:
    name: accounts

  profiles:
    active: prod

#  datasource:
#    url: jdbc:mysql://localhost:3306/accountsdb
#    username: root
#    password: root
#  jpa:
#    hibernate:
##      ddl-auto: create-drop
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: true
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"           # expose all endpoints including shutdown
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    shutdown:
      enabled: true            # enable shutdown endpoint

info:
  app:
    name: "accounts"
    description: "ezyPay Accounts Application"
    version: "1.0.0"

logging:
  level:
    com.microservices.accounts: DEBUG