spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sushantpaudel77/my-Banking-application-config-server"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

server:
  port: 8071

encrypt:
  key: ${ENCRYPT_KEY}

logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.web: INFO