server:
  http:
    listen_address: 0.0.0.0:9080

discovery.docker:
  host: unix:///var/run/docker.sock
  refresh_interval: 5s
  forward_to: [relabel.docker_jobs]

relabel.docker_jobs:
  rules:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
  forward_to: [loki.write]

loki.write:
  endpoint:
    url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

positions:
  filename: /tmp/positions.yaml
