auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_level: info

memberlist:
  join_members: [ "read", "write", "backend" ]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: [ '0.0.0.0' ]
  bind_port: 7946
  gossip_interval: 2s

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://backend:3100
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

# Query frontend configuration
frontend:
  scheduler_address: query-scheduler:9095
  compress_responses: true
  max_outstanding_per_tenant: 2048
  log_queries_longer_than: 10s

# Query scheduler configuration
query_scheduler:
  max_outstanding_requests_per_tenant: 2048
  grpc_client_config:
    max_send_msg_size: 104857600

# Query range configuration
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100


querier:
  max_concurrent: 4
  query_ingesters_within: 3h

# Write path configuration
distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_encoding: snappy
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  chunk_target_size: 1572864
  wal:
    dir: /loki/wal
    enabled: true

# Backend services
ruler:
  storage:
    type: s3
    s3:
      bucketnames: loki-ruler
      endpoint: minio:9000
      access_key_id: loki
      secret_access_key: supersecret
      insecure: true
      s3forcepathstyle: true
  rule_path: /tmp/loki/rules-temp
  ring:
    kvstore:
      store: memberlist
  enable_api: true

compactor:
  working_directory: /tmp/compactor
  retention_enabled: true
  delete_request_store: s3
  compaction_interval: 10m

index_gateway:
  mode: ring
  ring:
    kvstore:
      store: memberlist

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    cache_ttl: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 24h
  max_query_parallelism: 32
  max_query_length: 12000h
  max_query_series: 500
  max_streams_per_user: 0
  max_line_size: 256000